"""update on notif table

Revision ID: 229e5a666461
Revises: 5f77f8fe2182
Create Date: 2024-12-30 17:36:23.466736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229e5a666461'
down_revision = '5f77f8fe2182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
