"""update on notification table

Revision ID: 5f77f8fe2182
Revises: 6ecfb95ae75f
Create Date: 2024-12-29 13:14:13.417476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f77f8fe2182'
down_revision = '6ecfb95ae75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_real_time_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('is_real_time_sent')

    # ### end Alembic commands ###
